name: 🐛 Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: When I do X, Y happens instead of Z...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a DataAccessor with...
        2. Call get() with path...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: php
      placeholder: |
        <?php
        use event4u\DataHelpers\DataAccessor;
        
        $data = ['user' => ['name' => 'Alice']];
        $accessor = new DataAccessor($data);
        // ...
    validations:
      required: false

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      description: What version of PHP are you using?
      placeholder: "8.2.0"
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: What version of event4u/data-helpers are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: framework
    attributes:
      label: Framework (if applicable)
      options:
        - None (standalone PHP)
        - Laravel
        - Symfony
        - Doctrine
        - Other
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
    validations:
      required: false
