services:
    # Default configuration for services in this bundle
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    # DataMapper service (optional, can be used directly as static class)
    event4u\DataHelpers\DataMapper:
        public: true

    # MappedModel Value Resolver for automatic dependency injection
    event4u\DataHelpers\Frameworks\Symfony\MappedModelResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

