name: Code Quality

on:
  push:
    branches:
      - main
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml'
      - 'scripts/test-without-framework-deps.sh'
      - '.github/workflows/plain-php-tests.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml'
      - 'scripts/test-without-framework-deps.sh'
      - '.github/workflows/plain-php-tests.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Install dependencies (with all frameworks for analysis)
        run: composer update --prefer-dist --no-interaction

      - name: Run ECS
        run: vendor/bin/ecs check

      - name: Run Rector
        run: vendor/bin/rector process --dry-run
