name: Plain PHP Tests

on:
  push:
    branches:
      - main
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml'
      - 'scripts/test-without-framework-deps.sh'
      - '.github/workflows/plain-php-tests.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml'
      - 'scripts/test-without-framework-deps.sh'
      - '.github/workflows/plain-php-tests.yml'
  workflow_dispatch:

jobs:
  plain-php-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.2, 8.3, 8.4]

    name: Plain PHP Tests (PHP ${{ matrix.php }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-progress

      - name: Run Plain PHP Tests (without framework dependencies)
        run: |
          echo "🧪  Running Plain PHP Tests on PHP ${{ matrix.php }}..."
          chmod +x scripts/test-without-framework-deps.sh
          ./scripts/test-without-framework-deps.sh

